### ISSUE TITLE
CTarArcFile_BZip2内のヒープ二重解放バグ

### ISSUE THREAD

**Issue by ayakawa-m** [Claybird/tar32#2]
CTarArcFile_BZip2::read関数内部の以下の部分

`			BZ2_bzReadClose(&error, m_pbzFile);`
`			if (error != BZ_OK) return read;	//error`
` `
`			if (nUnused == 0 && myfeof(m_file)) return read;`

BZ2_bzReadCloseがBZ_OK、且つ、nUnused == 0 && myfeof(m_file)が真の場合、m_pbzFileが無効になっているのにもかかわらずNULLにクリアされておらず、この状態でCTarArcFile_BZip2::close関数が呼ばれた場合に一度解放されているm_pbzFileをもう一度解放しようとしてヒープが壊れます。

**Comment by Claybird** [comment]
ご指摘ありがとうございます。
NULLクリアを追加しました。
