### ISSUE TITLE
add support Zstandard

### ISSUE THREAD

**Issue by ayakawa-m** [Claybird/tar32#3]
Since Zstandard has become popular, add Zstandard support to tar32.dll?

**Comment by Claybird** [comment]
I think it's a good idea.
Shall I merge your code at http://ayakawa.o.oo7.jp/soft/ntutil.html#tar, so that to support 64bit in addition to Zstandard support?

**Comment by ayakawa-m** [comment]
It would be appreciated if support for 64-bit builds could also be added.
Is it necessary to create a separate issue for 64bit build?

**Comment by Claybird** [comment]
Thank you, but you don't have to. This issue is enough.
I think I can merge code and add some test cases within a few weeks or less.

**Comment by Claybird** [comment]
@ayakawa-m 
Finally, I think I've successfully merged your commit!
https://github.com/Claybird/tar32/releases/tag/Ver.2.48RC

**Comment by ayakawa-m** [comment]
I tested to compile & run, I think there is no problem :)

**Comment by Claybird** [comment]
Thank you for your contribution and checking!
